import os
import seaborn as sns
import warnings

sns.set_style("white")
warnings.filterwarnings("ignore")

DATA_PATH = "../input/all-dogs/"
ANNOTATION_PATH = "../input/Annotation"
CP_PATH = "../output/"

IMAGES = [DATA_PATH + p for p in os.listdir(DATA_PATH)]

seed = 2019
IMG_SIZE = 64
NUM_CLASSES = 120


CLASSES = [
    "Irish_wolfhound",
    "Gordon_setter",
    "Japanese_spaniel",
    "Samoyed",
    "Blenheim_spaniel",
    "malamute",
    "Tibetan_mastiff",
    "golden_retriever",
    "African_hunting_dog",
    "Saint_Bernard",
    "silky_terrier",
    "Leonberg",
    "coated_retriever",
    "briard",
    "schipperke",
    "Norwegian_elkhound",
    "Greater_Swiss_Mountain_dog",
    "Afghan_hound",
    "Weimaraner",
    "basset",
    "standard_schnauzer",
    "EntleBucher",
    "Newfoundland",
    "Brittany_spaniel",
    "Pomeranian",
    "bull_mastiff",
    "Maltese_dog",
    "beagle",
    "Old_English_sheepdog",
    "keeshond",
    "Irish_setter",
    "coated_retriever",
    "Sussex_spaniel",
    "Mexican_hairless",
    "dingo",
    "Shetland_sheepdog",
    "Doberman",
    "Dandie_Dinmont",
    "Saluki",
    "affenpinscher",
    "Irish_water_spaniel",
    "tan_coonhound",
    "Norfolk_terrier",
    "malinois",
    "miniature_schnauzer",
    "Sealyham_terrier",
    "Cardigan",
    "Kerry_blue_terrier",
    "chow",
    "standard_poodle",
    "Airedale",
    "Staffordshire_bullterrier",
    "Great_Dane",
    "Pembroke",
    "basenji",
    "haired_fox_terrier",
    "Great_Pyrenees",
    "Tibetan_terrier",
    "Bernese_mountain_dog",
    "West_Highland_white_terrier",
    "Lhasa",
    "miniature_poodle",
    "Boston_bull",
    "Walker_hound",
    "pug",
    "toy_poodle",
    "kuvasz",
    "papillon",
    "German_shepherd",
    "komondor",
    "Bedlington_terrier",
    "whippet",
    "Brabancon_griffon",
    "cairn",
    "borzoi",
    "coated_wheaten_terrier",
    "collie",
    "Welsh_springer_spaniel",
    "bloodhound",
    "Italian_greyhound",
    "Scotch_terrier",
    "dhole",
    "Bouvier_des_Flandres",
    "Norwich_terrier",
    "vizsla",
    "Irish_terrier",
    "kelpie",
    "redbone",
    "miniature_pinscher",
    "haired_pointer",
    "boxer",
    "Scottish_deerhound",
    "Border_collie",
    "American_Staffordshire_terrier",
    "toy_terrier",
    "English_setter",
    "Siberian_husky",
    "Pekinese",
    "Border_terrier",
    "giant_schnauzer",
    "cocker_spaniel",
    "Rhodesian_ridgeback",
    "bluetick",
    "Tzu",
    "Lakeland_terrier",
    "Eskimo_dog",
    "Labrador_retriever",
    "groenendael",
    "otterhound",
    "English_foxhound",
    "Appenzeller",
    "Ibizan_hound",
    "Chesapeake_Bay_retriever",
    "Rottweiler",
    "Yorkshire_terrier",
    "Australian_terrier",
    "French_bulldog",
    "English_springer",
    "clumber",
    "Chihuahua",
]

